#!/usr/bin/env python3
# Copyright (C) 2026 GammaOS
#
# Generate NanoOskArabic.h: a self-contained Arabic contextual-shaping table.
#
# The Nano OSK has no access to ICU's u_shapeArabic (libandroidicu is visibility
# restricted to ICU subpackages, and the stable libicu NDK surface does not
# export the shaping API). Arabic shaping is a small, well-defined table problem,
# so we generate the data here from the host Unicode database and ship a tiny
# shaping routine in NanoOsk.cpp.
#
# For every Arabic letter we emit its up-to-four contextual presentation forms
# (isolated / final / initial / medial) plus two join flags derived from which
# forms exist:
#     joinsRight = letter can connect to the PREVIOUS letter (has final/medial)
#     joinsLeft  = letter can connect to the NEXT letter     (has initial/medial)
# A dual-joining letter has all four forms; a right-joining letter (alef, dal,
# reh, waw, ...) has only isolated+final; a non-joining letter (hamza) has only
# isolated. We also emit the lam-alef ligatures, which collapse LAM + an alef
# variant into a single glyph.
#
# Usage:
#   python3 tools/osk/gen_osk_arabic.py \
#       --out frameworks/base/cmds/gammaos-nano/NanoOskArabic.h

import argparse
import unicodedata

# Arabic alef variants that ligate with a preceding LAM (U+0644).
LAM = 0x0644
ALEF_VARIANTS = (0x0622, 0x0623, 0x0625, 0x0627)


def build_forms():
    """base_cp -> {tag: pres_cp}, and (lam,alef) ligatures -> {tag: pres_cp}."""
    forms = {}
    ligs = {}
    blocks = list(range(0xFB50, 0xFE00)) + list(range(0xFE70, 0xFF00))
    for cp in blocks:
        d = unicodedata.decomposition(chr(cp))
        if not d or not d.startswith("<"):
            continue
        tag = d[1:d.index(">")]
        if tag not in ("isolated", "final", "initial", "medial"):
            continue
        bases = [int(p, 16) for p in d[d.index(">") + 1:].split()]
        if len(bases) == 1:
            forms.setdefault(bases[0], {})[tag] = cp
        elif len(bases) == 2:
            ligs.setdefault(tuple(bases), {})[tag] = cp
    return forms, ligs


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    forms, ligs = build_forms()

    out = []
    out.append("// AUTO-GENERATED by tools/osk/gen_osk_arabic.py. DO NOT EDIT.")
    out.append("// Arabic contextual-shaping table (replaces ICU u_shapeArabic).")
    out.append("")
    out.append("#ifndef GAMMAOS_NANO_OSK_ARABIC_H")
    out.append("#define GAMMAOS_NANO_OSK_ARABIC_H")
    out.append("")
    out.append("#include <cstdint>")
    out.append("")
    out.append("namespace android {")
    out.append("")
    out.append("// One Arabic base letter and its contextual presentation forms.")
    out.append("// A form value of 0 means the letter has no such form (fall back).")
    out.append("struct OskArShape {")
    out.append("    uint32_t base;")
    out.append("    uint16_t iso, fin, ini, med;")
    out.append("    uint8_t  joinsRight;  // connects to the previous letter")
    out.append("    uint8_t  joinsLeft;   // connects to the next letter")
    out.append("};")
    out.append("")
    out.append("static const OskArShape kOskArShape[] = {")
    for base in sorted(forms):
        f = forms[base]
        iso = f.get("isolated", 0)
        fin = f.get("final", 0)
        ini = f.get("initial", 0)
        med = f.get("medial", 0)
        jr = 1 if (fin or med) else 0
        jl = 1 if (ini or med) else 0
        name = unicodedata.name(chr(base), "?")
        out.append("    { 0x%04X, 0x%04X, 0x%04X, 0x%04X, 0x%04X, %d, %d },  // %s"
                   % (base, iso, fin, ini, med, jr, jl, name))
    out.append("};")
    out.append("static const int kOskArShapeCount = %d;" % len(forms))
    out.append("")
    out.append("// LAM (U+0644) + alef variant -> single ligature glyph.")
    out.append("struct OskArLamAlef { uint32_t alef; uint16_t iso, fin; };")
    out.append("static const OskArLamAlef kOskArLamAlef[] = {")
    for alef in ALEF_VARIANTS:
        lf = ligs.get((LAM, alef), {})
        iso = lf.get("isolated", 0)
        fin = lf.get("final", 0)
        if iso or fin:
            out.append("    { 0x%04X, 0x%04X, 0x%04X }," % (alef, iso, fin))
    out.append("};")
    out.append("static const int kOskArLamAlefCount = %d;"
               % sum(1 for a in ALEF_VARIANTS if (LAM, a) in ligs))
    out.append("")
    out.append("} // namespace android")
    out.append("")
    out.append("#endif // GAMMAOS_NANO_OSK_ARABIC_H")
    out.append("")

    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write("\n".join(out))
    print("Generated %s (%d letters, %d lam-alef ligatures)"
          % (args.out, len(forms),
             sum(1 for a in ALEF_VARIANTS if (LAM, a) in ligs)))


if __name__ == "__main__":
    main()
