#!/usr/bin/env python3
# Copyright (C) 2026 GammaOS
#
# Generate NanoOskKana.h: the romaji -> hiragana mapping table for the Nano OSK
# Japanese input method. This is the standard, finite "wapuro romaji" table
# (gojuon + youon + dakuten/handakuten). The runtime KanaInput engine layers
# the sokuon (small tsu from doubled consonants) and syllabic-n rules on top of
# this table, so only the direct syllable map lives here.
#
# Kanji conversion is intentionally NOT handled: there is no Japanese morphology
# dictionary in the tree, so the Nano IME produces hiragana (which is valid
# Japanese text). Kana->kanji is future work that needs a vendored dictionary.
#
# Usage:
#   python3 tools/osk/gen_osk_kana.py \
#       --out frameworks/base/cmds/gammaos-nano/NanoOskKana.h

import argparse

# romaji -> hiragana. Alternate spellings (shi/si, chi/ti, tsu/tu, fu/hu, ji/zi,
# ...) all map to the same kana so either input works.
KANA = {
    # gojuon
    "a": "あ", "i": "い", "u": "う", "e": "え", "o": "お",
    "ka": "か", "ki": "き", "ku": "く", "ke": "け", "ko": "こ",
    "sa": "さ", "shi": "し", "si": "し", "su": "す", "se": "せ", "so": "そ",
    "ta": "た", "chi": "ち", "ti": "ち", "tsu": "つ", "tu": "つ", "te": "て", "to": "と",
    "na": "な", "ni": "に", "nu": "ぬ", "ne": "ね", "no": "の",
    "ha": "は", "hi": "ひ", "fu": "ふ", "hu": "ふ", "he": "へ", "ho": "ほ",
    "ma": "ま", "mi": "み", "mu": "む", "me": "め", "mo": "も",
    "ya": "や", "yu": "ゆ", "yo": "よ",
    "ra": "ら", "ri": "り", "ru": "る", "re": "れ", "ro": "ろ",
    "wa": "わ", "wo": "を", "wi": "ゐ", "we": "ゑ",
    "nn": "ん",
    # dakuten
    "ga": "が", "gi": "ぎ", "gu": "ぐ", "ge": "げ", "go": "ご",
    "za": "ざ", "ji": "じ", "zi": "じ", "zu": "ず", "ze": "ぜ", "zo": "ぞ",
    "da": "だ", "di": "ぢ", "du": "づ", "de": "で", "do": "ど",
    "ba": "ば", "bi": "び", "bu": "ぶ", "be": "べ", "bo": "ぼ",
    "pa": "ぱ", "pi": "ぴ", "pu": "ぷ", "pe": "ぺ", "po": "ぽ",
    # youon
    "kya": "きゃ", "kyu": "きゅ", "kyo": "きょ",
    "sha": "しゃ", "shu": "しゅ", "sho": "しょ",
    "sya": "しゃ", "syu": "しゅ", "syo": "しょ",
    "cha": "ちゃ", "chu": "ちゅ", "cho": "ちょ",
    "tya": "ちゃ", "tyu": "ちゅ", "tyo": "ちょ",
    "nya": "にゃ", "nyu": "にゅ", "nyo": "にょ",
    "hya": "ひゃ", "hyu": "ひゅ", "hyo": "ひょ",
    "mya": "みゃ", "myu": "みゅ", "myo": "みょ",
    "rya": "りゃ", "ryu": "りゅ", "ryo": "りょ",
    "gya": "ぎゃ", "gyu": "ぎゅ", "gyo": "ぎょ",
    "ja": "じゃ", "ju": "じゅ", "jo": "じょ",
    "jya": "じゃ", "jyu": "じゅ", "jyo": "じょ",
    "bya": "びゃ", "byu": "びゅ", "byo": "びょ",
    "pya": "ぴゃ", "pyu": "ぴゅ", "pyo": "ぴょ",
    # standalone small vowels (xa/la prefix) - handy for combos
    "xtsu": "っ", "xtu": "っ",
    # punctuation
    "-": "ー", ".": "。", ",": "、",
}


def c_string(s):
    out = '"'
    for b in s.encode("utf-8"):
        if 0x20 <= b <= 0x7E and b not in (0x22, 0x5C):
            out += chr(b)
        elif b == 0x22:
            out += '\\"'
        elif b == 0x5C:
            out += "\\\\"
        else:
            out += "\\x%02x" % b
    return out + '"'


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    rows = sorted(KANA.items())   # sorted by romaji for binary search
    out = []
    out.append("// AUTO-GENERATED by tools/osk/gen_osk_kana.py. DO NOT EDIT.")
    out.append("// Romaji -> hiragana table for the Nano Japanese input method.")
    out.append("")
    out.append("#ifndef GAMMAOS_NANO_OSK_KANA_H")
    out.append("#define GAMMAOS_NANO_OSK_KANA_H")
    out.append("")
    out.append("namespace android {")
    out.append("")
    out.append("// One romaji spelling and the hiragana it produces. Sorted by")
    out.append("// `romaji` so the engine can binary-search and test prefixes.")
    out.append("struct OskKana { const char* romaji; const char* kana; };")
    out.append("static const OskKana kOskKana[] = {")
    for r, k in rows:
        out.append("    { %-8s, %-12s }," % (c_string(r), c_string(k)))
    out.append("};")
    out.append("static const int kOskKanaCount = %d;" % len(rows))
    out.append("")
    out.append("} // namespace android")
    out.append("")
    out.append("#endif // GAMMAOS_NANO_OSK_KANA_H")
    out.append("")
    with open(args.out, "w", encoding="utf-8") as f:
        f.write("\n".join(out))
    print("Generated %s (%d romaji entries)" % (args.out, len(rows)))


if __name__ == "__main__":
    main()
