#!/usr/bin/env python3
# Copyright (C) 2026 GammaOS
#
# Generate NanoOskKanji.h: a hiragana-reading -> kanji-candidate table for the
# Nano Japanese input method, so romaji input can be converted to kanji (not
# just hiragana).
#
# Source: the SKK-JISYO dictionary (skk-dev/dict), okuri-nasi entries, which are
# literally "reading /candidate1/candidate2/.../". The reading is normalized to
# hiragana (katakana readings folded down) so it matches what the romaji->kana
# engine produces. Candidate annotations (";...") are stripped.
#
# NOTE ON LICENSE: SKK-JISYO is distributed under the GPL. The generated table
# is therefore a derivative of GPL data. Keep that in mind before shipping.
#
# Usage:
#   python3 tools/osk/gen_osk_kanji.py \
#       --skk /path/to/SKK-JISYO.M \
#       --out frameworks/base/cmds/gammaos-nano/NanoOskKanji.h

import argparse

MAX_CAND = 8          # kanji candidates kept per reading
MAX_READING = 8       # skip very long readings (keep the table tight)

HIRA_LO, HIRA_HI = 0x3041, 0x3096
KATA_LO, KATA_HI = 0x30A1, 0x30F6
PROLONG = 0x30FC      # ー (allowed in readings)


def kata_to_hira(s):
    out = []
    for ch in s:
        cp = ord(ch)
        if KATA_LO <= cp <= KATA_HI:
            out.append(chr(cp - 0x60))
        else:
            out.append(ch)
    return "".join(out)


def is_hiragana_reading(s):
    for ch in s:
        cp = ord(ch)
        if not (HIRA_LO <= cp <= HIRA_HI or cp == PROLONG):
            return False
    return len(s) > 0


def parse_skk(path):
    entries = {}    # reading(hiragana) -> [candidates]
    with open(path, "rb") as f:
        for raw in f:
            try:
                line = raw.decode("euc_jp")
            except UnicodeDecodeError:
                continue
            if line.startswith(";") or " " not in line:
                continue
            key, rest = line.rstrip("\n").split(" ", 1)
            if not key or key[-1].isascii():     # skip okuri-ari (trailing latin)
                continue
            reading = kata_to_hira(key)
            if not is_hiragana_reading(reading) or len(reading) > MAX_READING:
                continue
            cands = []
            for c in rest.strip("/").split("/"):
                if not c:
                    continue
                c = c.split(";", 1)[0].strip()   # drop ;annotation
                if c and c not in cands:
                    cands.append(c)
            if cands:
                entries.setdefault(reading, [])
                for c in cands:
                    if c not in entries[reading]:
                        entries[reading].append(c)
    return entries


def c_string(s):
    out = '"'
    for b in s.encode("utf-8"):
        if 0x20 <= b <= 0x7E and b not in (0x22, 0x5C):
            out += chr(b)
        elif b == 0x22:
            out += '\\"'
        elif b == 0x5C:
            out += "\\\\"
        else:
            out += "\\x%02x" % b
    return out + '"'


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--skk", required=True)
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    entries = parse_skk(args.skk)
    readings = sorted(entries.keys())   # byte-sorted for binary search

    cand_flat = []
    rows = []
    for r in readings:
        cs = entries[r][:MAX_CAND]
        rows.append((r, len(cand_flat), len(cs)))
        cand_flat.extend(cs)

    out = []
    out.append("// AUTO-GENERATED by tools/osk/gen_osk_kanji.py. DO NOT EDIT.")
    out.append("// Hiragana reading -> kanji candidates (derived from SKK-JISYO,")
    out.append("// which is GPL-licensed).")
    out.append("")
    out.append("#ifndef GAMMAOS_NANO_OSK_KANJI_H")
    out.append("#define GAMMAOS_NANO_OSK_KANJI_H")
    out.append("")
    out.append("#include <cstdint>")
    out.append("")
    out.append("namespace android {")
    out.append("")
    out.append("// All kanji candidate strings, flat. Each reading owns a slice.")
    out.append("static const char* const kKjCand[] = {")
    line = "    "
    for c in cand_flat:
        tok = c_string(c) + ","
        if len(line) + len(tok) > 96:
            out.append(line); line = "    "
        line += tok
    if line.strip():
        out.append(line)
    out.append("};")
    out.append("static const int kKjCandCount = %d;" % len(cand_flat))
    out.append("")
    out.append("// Reading -> [candOff, candOff+candCount) in kKjCand. Sorted by")
    out.append("// reading (UTF-8 byte order) for binary search.")
    out.append("struct OskKjEntry { const char* reading; uint32_t candOff; uint16_t candCount; };")
    out.append("static const OskKjEntry kKjEntry[] = {")
    for r, off, cnt in rows:
        out.append("    { %-14s, %6d, %d }," % (c_string(r), off, cnt))
    out.append("};")
    out.append("static const int kKjEntryCount = %d;" % len(rows))
    out.append("")
    out.append("} // namespace android")
    out.append("")
    out.append("#endif // GAMMAOS_NANO_OSK_KANJI_H")
    out.append("")

    with open(args.out, "w", encoding="utf-8") as f:
        f.write("\n".join(out))
    print("Generated %s: %d readings, %d candidate slots"
          % (args.out, len(rows), len(cand_flat)))


if __name__ == "__main__":
    main()
