#pragma once

#include "KeyLayoutParser.h"

#include <linux/input.h>
#include <cmath>
#include <set>
#include <string>
#include <unordered_map>
#include <vector>

namespace gammapad {

struct CalibrationData {
    int center = 0;
    int min = -32768;
    int max = 32767;
    int deadzone = 4096;
    float sensitivity = 1.0f;
    bool invert = false;
};

struct AxisButtonTrigger {
    int axisCode;       // mapped axis code (matches virtual pad output)
    int buttonCode;     // BTN to emit
    int thresholdOn;    // absolute value for press
    int thresholdOff;   // absolute value for release (hysteresis)
    int axisMin;        // axis range min (for percentage computation)
    int axisMax;        // axis range max
    bool pressed;       // current state
    bool hijack;        // true = suppress ABS event, false = emit both
};

struct ComboMapping {
    int btn1;           // first source button code
    int btn2;           // second source button code
    int emitBtn;        // target button to emit when both sources held
    bool active;        // whether this combo is currently triggered
};

class InputTransformer {
public:
    InputTransformer();

    void loadConfig();

    // Transform a single input event in-place using per-device absinfo.
    // Returns false if the event should be dropped.
    bool transform(struct input_event& ev,
                   const std::unordered_map<int, AxisInfo>& deviceAbsInfo);

    // Set .kl-based device maps (called by GamepadManager after discovery)
    void setDeviceMaps(const std::unordered_map<int, int>& absMap,
                       const std::unordered_map<int, int>& keyMap);

    // Public getters for remap maps (used by GamepadManager for
    // detecting remap-induced code changes that require virtual device recreation)
    const std::unordered_map<int, int>& getButtonRemaps() const { return mButtonRemap; }
    const std::unordered_map<int, int>& getAxisRemaps() const { return mAxisRemap; }

    // Get extra events generated by axis-to-button triggers
    const std::vector<struct input_event>& getExtraEvents() const { return mExtraEvents; }
    void clearExtraEvents() { mExtraEvents.clear(); }

    // Get all button codes used by axis-to-button triggers
    std::set<int> getAxisButtonCodes() const;

    // Get all button codes emitted by combo mappings
    std::set<int> getComboEmitCodes() const;

    // Apply per-app overrides on top of the current global config.
    // btnRemapStr: "from:to,from:to" (merge with global, per-app wins on conflict)
    // comboMapStr: "btn1+btn2=emit,..." (appended to global combos)
    void applyPerAppOverrides(const std::string& btnRemapStr,
                              const std::string& comboMapStr);

    // When mouse mode is active, skip analog/DPAD conversions, axis-to-button
    // triggers, and global sensitivity so MouseMode gets clean values.
    void setMouseMode(bool active) { mMouseModeActive = active; }

private:
    int applyCalibration(int axis, int value);
    int applyDeadzone(int value, int deadzone);
    int applySensitivity(int value, float sensitivity);

    // Get the partner axis for circular deadzone (X↔Y, RX↔RY)
    static int getStickPartner(int axis);

    // Returns true if the axis should be suppressed (hijack mode matched)
    bool processAxisButton(int axisCode, int value);

    // Process button combo logic. Returns true if the event was consumed
    // (don't forward to virtual pad). May generate extra events.
    bool processCombo(struct input_event& ev);

    // Parse combo map string "btn1+btn2=emit,..." and append to mCombos
    void parseCombos(const std::string& comboStr);

    // .kl-based device maps (scancode -> final code)
    std::unordered_map<int, int> mDeviceAbsMap;
    std::unordered_map<int, int> mDeviceKeyMap;

    // Button remap: from key code -> to key code
    std::unordered_map<int, int> mButtonRemap;
    // Axis remap: from axis code -> to axis code
    std::unordered_map<int, int> mAxisRemap;
    // Per-axis calibration
    std::unordered_map<int, CalibrationData> mCalibration;

    // Last normalized value per axis (post center-offset + range-normalize, pre-deadzone)
    std::unordered_map<int, int> mLastNormalized;

    bool mAnalogToDpad;
    bool mDpadToAnalog;
    int mDpadThreshold; // 0-32767 scaled from percentage

    // Passthrough blacklist: suppress these button codes from reaching apps
    std::set<int> mBlacklistPass;

    // Global quick-access toggles (set from QS tiles / Settings)
    bool mAbxySwap;
    bool mInvertLeft;
    bool mInvertRight;
    int mGlobalSensitivity;   // -3..+3

    // Axis-to-button triggers
    std::vector<AxisButtonTrigger> mAxisButtons;
    // Extra events generated by axis-to-button / combos (key press/release + SYN)
    std::vector<struct input_event> mExtraEvents;

    // Button combo mappings
    std::vector<ComboMapping> mCombos;
    // Buttons currently physically held (post-KL, post-ABXY, post-user-remap)
    std::set<int> mPhysicalHeld;
    // Buttons currently pressed on the virtual gamepad (forwarded to apps)
    std::set<int> mVirtualHeld;

    // Mouse mode flag: skip conversions, axis-to-button, global sensitivity
    bool mMouseModeActive;
};

} // namespace gammapad
