#pragma once

#include "KeyLayoutParser.h"

#include <linux/input.h>
#include <cmath>
#include <cstdint>
#include <functional>
#include <set>
#include <string>
#include <unordered_map>
#include <vector>

namespace gammapad {

// Action a button press can trigger (short or long press).
enum ActionType {
    ACT_NONE = 0,
    ACT_KEY,       // arg = decimal evdev code to emit (BTN_* via gamepad, KEY_* via keyboard)
    ACT_APP,       // arg = package name to launch
    ACT_ACTIVITY,  // arg = pkg/Component to launch
    ACT_PROP,      // arg = "name=value" to set
    ACT_SHELL,     // arg = shell command to run
    ACT_DPAD_SWAP, // no arg; toggle the DPAD/Analog swap (both analog_to_dpad and
                   // dpad_to_analog) + bump config_version, exactly like the QS tile
};

// Per-button action rule: what a short press and a long press do.
struct ButtonAction {
    ActionType shortType = ACT_NONE;
    std::string shortArg;
    ActionType longType = ACT_NONE;
    std::string longArg;
    int holdMs = 0;    // long-press threshold; forced > 0 when longType is set
};

// Runtime per-button hold state for the action model.
struct ActionPendState {
    bool pending = false;      // press seen, awaiting release/hold decision
    bool longFired = false;    // long action already fired for this hold
    int64_t pressTimeMs = 0;
};

// Callback that actually executes a fired action (owned by GamepadManager,
// which holds the virtual devices and can fork).  Runs on the daemon thread.
using ActionExec = std::function<void(int type, const std::string& arg)>;

struct CalibrationData {
    int center = 0;
    int min = -32768;
    int max = 32767;
    int deadzone = 4096;
    float sensitivity = 1.0f;
    bool invert = false;
};

struct AxisButtonTrigger {
    int axisCode;       // mapped axis code (matches virtual pad output)
    int buttonCode;     // BTN to emit
    int thresholdOn;    // absolute value for press
    int thresholdOff;   // absolute value for release (hysteresis)
    int axisMin;        // axis range min (for percentage computation)
    int axisMax;        // axis range max
    bool pressed;       // current state
    bool hijack;        // true = suppress ABS event, false = emit both
};

// Button-to-axis rule: a digital button drives an analog axis. When keepButton
// is set, the original digital button event is forwarded as well.
struct ButtonAxisRule {
    int axis;           // target axis code (e.g. ABS_BRAKE / ABS_GAS)
    int value;          // value emitted on press (release always emits 0)
    bool keepButton;    // also forward the original digital button event
};

struct ComboMapping {
    int btn1;           // first source button code
    int btn2;           // second source button code
    int emitBtn;        // target button to emit when both sources held
    bool active;        // whether this combo is currently triggered
};

class InputTransformer {
public:
    InputTransformer();

    void loadConfig();

    // Transform a single input event in-place using per-device absinfo.
    // Returns false if the event should be dropped.
    bool transform(struct input_event& ev,
                   const std::unordered_map<int, AxisInfo>& deviceAbsInfo);

    // Set .kl-based device maps (called by GamepadManager after discovery)
    void setDeviceMaps(const std::unordered_map<int, int>& absMap,
                       const std::unordered_map<int, int>& keyMap);

    // Public getters for remap maps (used by GamepadManager for
    // detecting remap-induced code changes that require virtual device recreation)
    const std::unordered_map<int, int>& getButtonRemaps() const { return mButtonRemap; }
    const std::unordered_map<int, int>& getAxisRemaps() const { return mAxisRemap; }

    // Get extra events generated by axis-to-button triggers
    const std::vector<struct input_event>& getExtraEvents() const { return mExtraEvents; }
    void clearExtraEvents() { mExtraEvents.clear(); }

    // Get all button codes used by axis-to-button triggers
    std::set<int> getAxisButtonCodes() const;

    // Get all target axis codes used by button-to-axis rules (btn_axis), so the
    // virtual pad advertises them.
    std::set<int> getButtonAxisCodes() const;

    // Get all button codes emitted by combo mappings
    std::set<int> getComboEmitCodes() const;

    // Apply per-app overrides on top of the current global config.
    // btnRemapStr: "from:to,from:to" (merge with global, per-app wins on conflict)
    // comboMapStr: "btn1+btn2=emit,..." (appended to global combos)
    void applyPerAppOverrides(const std::string& btnRemapStr,
                              const std::string& comboMapStr);

    // Register the executor that fires actions (key emit / launch / setprop / shell).
    void setActionCallback(ActionExec cb) { mActionCb = std::move(cb); }

    // Define/replace a button-action rule (used by loadConfig for globals and by
    // GamepadManager for per-app overrides).  shortStr/longStr are "type=arg".
    void setButtonAction(int code, int holdMs,
                         const std::string& shortStr, const std::string& longStr);
    void clearButtonActions() { mButtonActions.clear(); mActionPend.clear(); }

    // Fire any long-press actions whose hold threshold has elapsed.  Call
    // periodically from the run loop.
    void checkActionTimeouts();

    // Milliseconds until the next pending long-press fires, or -1 if none
    // pending.  Used to shorten the epoll timeout so long presses are crisp.
    int nextActionTimeoutMs();

    // All evdev codes any action rule can emit (ACT_KEY targets), so the
    // virtual devices can advertise them.
    std::set<int> getActionKeyCodes() const;

    bool hasButtonActions() const { return !mButtonActions.empty(); }

    // When mouse mode is active, skip analog/DPAD conversions, axis-to-button
    // triggers, and global sensitivity so MouseMode gets clean values.
    void setMouseMode(bool active) { mMouseModeActive = active; }

    // Mark axis codes that should be treated as sticks even though they share
    // codes with triggers (e.g., ABS_Z/ABS_RZ when the device uses them as
    // the right stick instead of triggers).
    void setForceStickAxes(const std::set<int>& axes) { mForceStickAxes = axes; }

    // Enable conversion of DPAD key events (KEY_UP/DOWN/LEFT/RIGHT) to
    // ABS_HAT0X/ABS_HAT0Y axis events.  Used when the source device has
    // DPAD buttons but no HAT axes.
    void setDpadKeysToHat(bool enable) { mDpadKeysToHat = enable; }

private:
    int applyCalibration(int axis, int value);
    int applyDeadzone(int value, int deadzone);
    int applySensitivity(int value, float sensitivity);

    // Get the partner axis for circular deadzone (X↔Y, RX↔RY)
    static int getStickPartner(int axis);

    // Returns true if the axis should be suppressed (hijack mode matched)
    bool processAxisButton(int axisCode, int value);

    // Process button combo logic. Returns true if the event was consumed
    // (don't forward to virtual pad). May generate extra events.
    bool processCombo(struct input_event& ev);

    // Parse combo map string "btn1+btn2=emit,..." and append to mCombos
    void parseCombos(const std::string& comboStr);

    // Button-action model helpers.
    // Returns true if the event was consumed (do not forward normally).
    bool processButtonAction(struct input_event& ev, const ButtonAction& a);
    void fireAction(ActionType type, const std::string& arg);
    void emitNormalTap(int code);   // replay a normal press+release of a button
    static ActionType parseActionSpec(const std::string& spec, std::string& argOut);
    static int64_t nowMs();

    // .kl-based device maps (scancode -> final code)
    std::unordered_map<int, int> mDeviceAbsMap;
    std::unordered_map<int, int> mDeviceKeyMap;

    // Button remap: from key code -> to key code
    std::unordered_map<int, int> mButtonRemap;
    // Axis remap: from axis code -> to axis code
    std::unordered_map<int, int> mAxisRemap;
    // Button-to-axis: source button code -> rule. A digital button emulates an
    // analog axis (e.g. L2/R2 -> ABS_BRAKE/ABS_GAS trigger): press emits the
    // value, release emits 0. When keepButton is set, the original digital button
    // event is ALSO forwarded (so apps that read L2/R2 as a button still see it).
    std::unordered_map<int, ButtonAxisRule> mButtonToAxis;
    // Per-axis calibration
    std::unordered_map<int, CalibrationData> mCalibration;

    // Last normalized value per axis (post center-offset + range-normalize, pre-deadzone)
    std::unordered_map<int, int> mLastNormalized;
    // Last post-calibration output per axis (for circle-to-square partner lookup)
    std::unordered_map<int, int> mLastOutput;

    bool mAnalogToDpad;
    bool mDpadToAnalog;
    int mDpadThreshold; // 0-32767 scaled from percentage

    // Passthrough blacklist: suppress these button codes from reaching apps
    std::set<int> mBlacklistPass;

    // Global quick-access toggles (set from QS tiles / Settings)
    bool mAbxySwap;
    bool mInvertLeft;
    bool mInvertRight;
    int mGlobalSensitivity;   // -3..+3

    // Axis-to-button triggers
    std::vector<AxisButtonTrigger> mAxisButtons;
    // Extra events generated by axis-to-button / combos (key press/release + SYN)
    std::vector<struct input_event> mExtraEvents;

    // Per-button action rules (keyed by mapped code) + runtime hold state.
    std::unordered_map<int, ButtonAction> mButtonActions;
    std::unordered_map<int, ActionPendState> mActionPend;
    ActionExec mActionCb;

    // Button combo mappings
    std::vector<ComboMapping> mCombos;
    // Buttons currently physically held (post-KL, post-ABXY, post-user-remap)
    std::set<int> mPhysicalHeld;
    // Buttons currently pressed on the virtual gamepad (forwarded to apps)
    std::set<int> mVirtualHeld;

    // Mouse mode flag: skip conversions, axis-to-button, global sensitivity
    bool mMouseModeActive;

    // Axes forced to stick normalization (bipolar, centered at 0)
    std::set<int> mForceStickAxes;

    // DPAD key → HAT axis conversion
    bool mDpadKeysToHat;
    bool mDpadUpHeld, mDpadDownHeld, mDpadLeftHeld, mDpadRightHeld;
};

} // namespace gammapad
