# SPDX-FileCopyrightText: 2024 The LineageOS Project
# SPDX-License-Identifier: Apache-2.0

version = 1
SPDX-PackageName = "Backgrounds"
SPDX-PackageSupplier = "The LineageOS Project"
SPDX-PackageDownloadLocation = "https://github.com/LineageOS/android_packages_apps_Backgrounds"

[[annotations]]
path = ["res_1080p/drawable-nodpi/*.jpg", "res_1440p/drawable-nodpi/*.jpg"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 The LineageOS Project"
SPDX-License-Identifier = "Apache-2.0"
