# SPDX-FileCopyrightText: 2024 The LineageOS Project
# SPDX-License-Identifier: Apache-2.0

version = 1
SPDX-PackageName = "ExactCalculator"
SPDX-PackageSupplier = "The LineageOS Project"
SPDX-PackageDownloadLocation = "https://github.com/LineageOS/android_packages_apps_ExactCalculator"

[[annotations]]
path = [".gitignore"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2014 The Android Open Source Project"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [".github/workflows/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 The LineageOS Project"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["gradle/wrapper/**", "gradlew*"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2007-2023 Gradle, Inc."
SPDX-License-Identifier = "Apache-2.0"
