[versions]
# For more info on Android Studio <-> AGP compatibilty, see:
#   http://go/android-dev/studio/preview/features#agp-previews
# For all available versions, see:
#   http://go/gmaven-index#com.android.library:com.android.library.gradle.plugin
android-gradle-plugin = "8.3.0-alpha07"
android-studio = "2023.2.1 Canary 7"

idea-ext-gradle-plugin = "1.1.7"
errorprone-gradle-plugin = "1.2.0"
errorprone-annotations-gradle-plugin = "2.15.0"
googleTruthVersion = "1.1.3"
guava = "30.0-android"
javaxInject = "1"
# http://cs/h/android/platform/superproject/main/+/main:external/kotlinc/build.txt
kotlin = "1.9.0"
# http://cs/h/android/platform/superproject/main/+/main:external/kotlinx.coroutines/METADATA
kotlinCoroutineVersion = "1.7.2"
legacySupportV4 = "1.0.0"
mockito = "2.28.3"
protobuf-gradle-plugin = "0.9.4"
protobuf = "3.8.0"
# TODO(b/280326338): Track //external/robolectric version
robolectric = "4.11-SNAPSHOT"
# http://cs/h/android/platform/superproject/main/+/main:external/junit/version
junit = "4.13.2"
lottie = "5.2.0"
androidx-benchmark = "1.2.0-rc01"
# http://cs/h/android/platform/superproject/main/+/main:external/dagger2/METADATA?l=14
dagger = "2.47"
hilt = "2.47"
testng = "7.8.0"

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
protobuf = { id = "com.google.protobuf", version.ref = "protobuf-gradle-plugin" }

[libraries]
androidx-annotation = { module = "androidx.annotation:annotation" }
androidx-appcompat = { module = "androidx.appcompat:appcompat" }
androidx-core = { module = "androidx.core:core" }
android-support-v7-appcompat = { module = "com.android.support:appcompat-v7", version = "28.0.0" }
androidx-legacy-support-core-ui = { module = "androidx.legacy:legacy-support-core-ui" }
androidx-legacy-support-v4 = { module = "androidx.legacy:legacy-support-v4", version.ref = "legacySupportV4" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview" }
androidx-window = { module = "androidx.window:window" }
com-google-android-material = { module = "com.google.android.material:material" }
androidx-ktx = { module = "androidx.core:core-ktx" }
errorprone-annotations = { module = "com.google.errorprone:error_prone_annotations", version.ref = "errorprone-annotations-gradle-plugin" }
espresso-contrib = { module = "androidx.test.espresso:espresso-contrib" }
espresso-core = { module = "androidx.test.espresso:espresso-core" }
espresso-intents = { module = "androidx.test.espresso:espresso-intents" }
google-truth = { module = "com.google.truth:truth", version.ref = "googleTruthVersion" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
javax-inject = { module = "javax.inject:javax.inject", version.ref = "javaxInject" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-stdlib-jdk7 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk7", version.ref = "kotlin" }
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinCoroutineVersion" }
lifecycle-common-java8 = { module = "androidx.lifecycle:lifecycle-common-java8" }
lifecycle-extensions = { module = "androidx.lifecycle:lifecycle-extensions" }
mockitoInline = { module = "com.linkedin.dexmaker:dexmaker-mockito-inline", version.ref = "mockito" }
mockitoInlineExtended = { module = "com.linkedin.dexmaker:dexmaker-mockito-inline-extended", version.ref = "mockito" }
mockitoKotlin = { module = "org.mockito.kotlin:mockito-kotlin", version = "2.2.11" }
protobuf-javalite = { module = "com.google.protobuf:protobuf-javalite", version.ref = "protobuf" }
protobuf-protoc = { module = "com.google.protobuf:protoc", version.ref = "protobuf" }
rules = { module = "androidx.test:rules" }
androidx-test-rules = { module = "androidx.test:rules" }
androidx-test-core = { module = "androidx.test:core" }
scriptClasspath-nullaway = { module = "net.ltgt.gradle:gradle-nullaway-plugin", version.ref = "errorprone-gradle-plugin" }
scriptClasspath-android = { module = "com.android.tools.build:gradle", version.ref = "android-gradle-plugin" }
scriptClasspath-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
scriptClasspath-errorprone = { module = "net.ltgt.gradle:gradle-errorprone-plugin", version.ref = "errorprone-gradle-plugin" }
scriptClasspath-protobuf = { module = "com.google.protobuf:protobuf-gradle-plugin", version.ref = "protobuf-gradle-plugin" }
scriptClasspath-hilt = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
truth = { module = "androidx.test.ext:truth" }
androidx-benchmark-macro = { module = "androidx.benchmark:benchmark-macro", version.ref = "androidx-benchmark" }
androidx-benchmark-common = { module = "androidx.benchmark:benchmark-common", version.ref = "androidx-benchmark" }
androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx" }
androidx-junit-ktx = { group = "androidx.test.ext", name = "junit-ktx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
testng = { module = "org.testng:testng", version.ref = "testng" }
# http://cs/h/googleplex-android/platform/superproject/main/+/main:external/lottie/METADATA
com-airbnb-android-lottie = { group = "com.airbnb.android", name = "lottie", version.ref = "lottie" }
androidx-appsearch = { group = "androidx.appsearch", name = "appsearch", version = "1.1.0-alpha03" }
androidx-appsearch-platform-storage = { group = "androidx.appsearch", name = "appsearch-platform-storage", version = "1.1.0-alpha03" }
androidx-appsearch-builtin-types = { group = "androidx.appsearch", name = "appsearch-builtin-types", version = "1.1.0-alpha03" }
androidx-concurrent-futures-ktx = { group = "androidx.concurrent", name = "concurrent-futures-ktx", version = "1.2.0-alpha02" }
dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger-android = { module = "com.google.dagger:dagger-android", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
dagger-android-processor = { module = "com.google.dagger:dagger-android-processor", version.ref = "dagger" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }
