# SPDX-FileCopyrightText: 2024 The LineageOS Project
# SPDX-License-Identifier: Apache-2.0

version = 1
SPDX-PackageName = "SetupWizard"
SPDX-PackageSupplier = "The LineageOS Project"
SPDX-PackageDownloadLocation = "https://github.com/LineageOS/android_packages_apps_SetupWizard"

[[annotations]]
path = ["res/raw/lottie_system_nav_2_button.json", "res/raw/lottie_system_nav_3_button.json", "res/raw/lottie_system_nav_fully_gestural.json"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2019 The Android Open Source Project"
SPDX-License-Identifier = "Apache-2.0"
