#!/usr/bin/env python3
# Generate NanoScraperDevCreds.gen.h (gitignored) from screenscraper_dev.local.txt
# (also gitignored). The ScreenScraper developer credentials are XOR-obfuscated
# against a random per-run key and each is split into two chunks, so they never
# appear as a readable string in the shipped image and are never committed.
#
# Run from this directory after filling in screenscraper_dev.local.txt:
#     python3 gen_ss_creds.py
#
# Then rebuild gammaos-nano. To rotate or clear the credentials, edit the .txt and
# re-run, or delete NanoScraperDevCreds.gen.h to ship without built-in credentials.

import os
import secrets
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "screenscraper_dev.local.txt")
OUT = os.path.join(HERE, "NanoScraperDevCreds.gen.h")


def read_creds(path):
    if not os.path.exists(path):
        sys.exit("error: %s not found. Copy the values into it first." % path)
    vals = {}
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, _, v = line.partition("=")
            vals[k.strip()] = v.strip()
    return vals


def obfuscate(plain, key):
    b = plain.encode("utf-8")
    x = bytes(b[i] ^ key[i % len(key)] for i in range(len(b)))
    half = (len(x) + 1) // 2
    return x[:half], x[half:]


def carr(name, data):
    body = ", ".join("0x%02x" % c for c in data) if data else "0"
    return "static const unsigned char %s[] = { %s };" % (name, body)


def main():
    v = read_creds(SRC)
    devid = v.get("devid", "")
    devpw = v.get("devpassword", "")
    softname = v.get("softname", "gammaos-nano") or "gammaos-nano"
    if not devid or not devpw:
        sys.exit("error: fill in both devid and devpassword in %s" % SRC)

    key = secrets.token_bytes(32)
    id1, id2 = obfuscate(devid, key)
    pw1, pw2 = obfuscate(devpw, key)

    # basic sanity: softname must be a plain C string literal
    if '"' in softname or "\\" in softname:
        sys.exit("error: softname must not contain quotes or backslashes")

    lines = [
        "// GENERATED by gen_ss_creds.py - DO NOT COMMIT, DO NOT EDIT BY HAND.",
        "// XOR-obfuscated, split ScreenScraper developer credentials.",
        "#pragma once",
        "#define NANO_SS_HAVE_DEV_CREDS 1",
        '#define NANO_SS_SOFTNAME "%s"' % softname,
        carr("kNanoSsKey", key),
        carr("kNanoSsID1", id1),
        carr("kNanoSsID2", id2),
        carr("kNanoSsPW1", pw1),
        carr("kNanoSsPW2", pw2),
        "",
    ]
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    os.chmod(OUT, 0o600)

    # Force a recompile of the translation unit that consumes the credentials.
    # The generated header is pulled in via __has_include, which the build's
    # dependency tracker does not record when the file was previously absent, so
    # without this touch a rebuild would keep the stale object and ignore the
    # (re)generated credentials.
    consumer = os.path.join(HERE, "NanoMenuScraper.cpp")
    if os.path.exists(consumer):
        os.utime(consumer, None)

    print("wrote %s (softname=%s, devid %d bytes, devpassword %d bytes)"
          % (OUT, softname, len(devid), len(devpw)))
    print("NOTE: %s and %s are gitignored. Never commit either." % (
        os.path.basename(OUT), os.path.basename(SRC)))


if __name__ == "__main__":
    main()
