// AUTO-GENERATED by tools/osk/gen_osk_extra.py. DO NOT EDIT.
// Non-Latin OSK keyboards (not part of the Leanback IME).

#ifndef GAMMAOS_NANO_OSK_LAYOUTS_EXTRA_H
#define GAMMAOS_NANO_OSK_LAYOUTS_EXTRA_H

#include "NanoOskTypes.h"

namespace android {

static const OskKey kXKeys_korean_r0[] = {
    {   49, "1"         , GLYPH_NONE     , 0.000000f, 0.065421f, true , false,  -1, false },
    {   50, "2"         , GLYPH_NONE     , 0.093458f, 0.065421f, false, false,  -1, false },
    {   51, "3"         , GLYPH_NONE     , 0.186916f, 0.065421f, false, false,  -1, false },
    {   52, "4"         , GLYPH_NONE     , 0.280374f, 0.065421f, false, false,  -1, false },
    {   53, "5"         , GLYPH_NONE     , 0.373832f, 0.065421f, false, false,  -1, false },
    {   54, "6"         , GLYPH_NONE     , 0.467290f, 0.065421f, false, false,  -1, false },
    {   55, "7"         , GLYPH_NONE     , 0.560748f, 0.065421f, false, false,  -1, false },
    {   56, "8"         , GLYPH_NONE     , 0.654206f, 0.065421f, false, false,  -1, false },
    {   57, "9"         , GLYPH_NONE     , 0.747664f, 0.065421f, false, false,  -1, false },
    {   48, "0"         , GLYPH_NONE     , 0.841121f, 0.065421f, false, false,  -1, false },
    {   -5, "Delete"    , GLYPH_DELETE   , 0.934579f, 0.065421f, false, true ,  -1, false },
};
static const OskKey kXKeys_korean_r1[] = {
    { 12610, "\xe3" "\x85" "\x82", GLYPH_NONE     , 0.046729f, 0.065421f, true , false,  -1, false },
    { 12616, "\xe3" "\x85" "\x88", GLYPH_NONE     , 0.140187f, 0.065421f, false, false,  -1, false },
    { 12599, "\xe3" "\x84" "\xb7", GLYPH_NONE     , 0.233645f, 0.065421f, false, false,  -1, false },
    { 12593, "\xe3" "\x84" "\xb1", GLYPH_NONE     , 0.327103f, 0.065421f, false, false,  -1, false },
    { 12613, "\xe3" "\x85" "\x85", GLYPH_NONE     , 0.420561f, 0.065421f, false, false,  -1, false },
    { 12635, "\xe3" "\x85" "\x9b", GLYPH_NONE     , 0.514019f, 0.065421f, false, false,  -1, false },
    { 12629, "\xe3" "\x85" "\x95", GLYPH_NONE     , 0.607477f, 0.065421f, false, false,  -1, false },
    { 12625, "\xe3" "\x85" "\x91", GLYPH_NONE     , 0.700935f, 0.065421f, false, false,  -1, false },
    { 12624, "\xe3" "\x85" "\x90", GLYPH_NONE     , 0.794393f, 0.065421f, false, false,  -1, false },
    { 12628, "\xe3" "\x85" "\x94", GLYPH_NONE     , 0.887850f, 0.065421f, false, true ,  -1, false },
};
static const OskKey kXKeys_korean_r2[] = {
    { 12609, "\xe3" "\x85" "\x81", GLYPH_NONE     , 0.093458f, 0.065421f, true , false,  -1, false },
    { 12596, "\xe3" "\x84" "\xb4", GLYPH_NONE     , 0.186916f, 0.065421f, false, false,  -1, false },
    { 12615, "\xe3" "\x85" "\x87", GLYPH_NONE     , 0.280374f, 0.065421f, false, false,  -1, false },
    { 12601, "\xe3" "\x84" "\xb9", GLYPH_NONE     , 0.373832f, 0.065421f, false, false,  -1, false },
    { 12622, "\xe3" "\x85" "\x8e", GLYPH_NONE     , 0.467290f, 0.065421f, false, false,  -1, false },
    { 12631, "\xe3" "\x85" "\x97", GLYPH_NONE     , 0.560748f, 0.065421f, false, false,  -1, false },
    { 12627, "\xe3" "\x85" "\x93", GLYPH_NONE     , 0.654206f, 0.065421f, false, false,  -1, false },
    { 12623, "\xe3" "\x85" "\x8f", GLYPH_NONE     , 0.747664f, 0.065421f, false, false,  -1, false },
    { 12643, "\xe3" "\x85" "\xa3", GLYPH_NONE     , 0.841121f, 0.065421f, false, true ,  -1, false },
};
static const OskKey kXKeys_korean_r3[] = {
    { 12619, "\xe3" "\x85" "\x8b", GLYPH_NONE     , 0.093458f, 0.065421f, true , false,  -1, false },
    { 12620, "\xe3" "\x85" "\x8c", GLYPH_NONE     , 0.186916f, 0.065421f, false, false,  -1, false },
    { 12618, "\xe3" "\x85" "\x8a", GLYPH_NONE     , 0.280374f, 0.065421f, false, false,  -1, false },
    { 12621, "\xe3" "\x85" "\x8d", GLYPH_NONE     , 0.373832f, 0.065421f, false, false,  -1, false },
    { 12640, "\xe3" "\x85" "\xa0", GLYPH_NONE     , 0.467290f, 0.065421f, false, false,  -1, false },
    { 12636, "\xe3" "\x85" "\x9c", GLYPH_NONE     , 0.560748f, 0.065421f, false, false,  -1, false },
    { 12641, "\xe3" "\x85" "\xa1", GLYPH_NONE     , 0.654206f, 0.065421f, false, false,  -1, false },
    {   44, ","         , GLYPH_NONE     , 0.747664f, 0.065421f, false, false,  -1, false },
    {   46, "."         , GLYPH_NONE     , 0.841121f, 0.065421f, false, true ,  -1, false },
};
static const OskKey kXKeys_korean_r4[] = {
    {   -2, "?!#"       , GLYPH_SYMBOLS  , 0.000000f, 0.065421f, true , false,  -1, false },
    {   -1, "Shift"     , GLYPH_SHIFT_OFF, 0.093458f, 0.065421f, false, false,  -1, false },
    {   32, "Space"     , GLYPH_SPACE    , 0.186916f, 0.626168f, false, false,  -1, false },
    {   -3, "Left"      , GLYPH_LEFT     , 0.841121f, 0.065421f, false, false,  -1, false },
    {   -4, "Right"     , GLYPH_RIGHT    , 0.934579f, 0.065421f, false, true ,  -1, false },
};
static const OskRow kXRows_korean[] = {
    { 0.000000f, 0.162791f, true , false, kXKeys_korean_r0, 11 },
    { 0.209302f, 0.162791f, false, false, kXKeys_korean_r1, 10 },
    { 0.418605f, 0.162791f, false, false, kXKeys_korean_r2, 9 },
    { 0.627907f, 0.162791f, false, false, kXKeys_korean_r3, 9 },
    { 0.837209f, 0.162791f, false, true , kXKeys_korean_r4, 5 },
};
static const OskKeyboard kKb_korean = { kXRows_korean, 5 };

static const OskKey kXKeys_russian_r0[] = {
    {   49, "1"         , GLYPH_NONE     , 0.000000f, 0.065421f, true , false,  -1, false },
    {   50, "2"         , GLYPH_NONE     , 0.093458f, 0.065421f, false, false,  -1, false },
    {   51, "3"         , GLYPH_NONE     , 0.186916f, 0.065421f, false, false,  -1, false },
    {   52, "4"         , GLYPH_NONE     , 0.280374f, 0.065421f, false, false,  -1, false },
    {   53, "5"         , GLYPH_NONE     , 0.373832f, 0.065421f, false, false,  -1, false },
    {   54, "6"         , GLYPH_NONE     , 0.467290f, 0.065421f, false, false,  -1, false },
    {   55, "7"         , GLYPH_NONE     , 0.560748f, 0.065421f, false, false,  -1, false },
    {   56, "8"         , GLYPH_NONE     , 0.654206f, 0.065421f, false, false,  -1, false },
    {   57, "9"         , GLYPH_NONE     , 0.747664f, 0.065421f, false, false,  -1, false },
    {   48, "0"         , GLYPH_NONE     , 0.841121f, 0.065421f, false, false,  -1, false },
    {   -5, "Delete"    , GLYPH_DELETE   , 0.934579f, 0.065421f, false, true ,  -1, false },
};
static const OskKey kXKeys_russian_r1[] = {
    { 1081, "\xd0" "\xb9", GLYPH_NONE     , 0.000000f, 0.065421f, true , false,  -1, true  },
    { 1094, "\xd1" "\x86", GLYPH_NONE     , 0.093458f, 0.065421f, false, false,  -1, true  },
    { 1091, "\xd1" "\x83", GLYPH_NONE     , 0.186916f, 0.065421f, false, false,  -1, true  },
    { 1082, "\xd0" "\xba", GLYPH_NONE     , 0.280374f, 0.065421f, false, false,  -1, true  },
    { 1077, "\xd0" "\xb5", GLYPH_NONE     , 0.373832f, 0.065421f, false, false,  -1, true  },
    { 1085, "\xd0" "\xbd", GLYPH_NONE     , 0.467290f, 0.065421f, false, false,  -1, true  },
    { 1075, "\xd0" "\xb3", GLYPH_NONE     , 0.560748f, 0.065421f, false, false,  -1, true  },
    { 1096, "\xd1" "\x88", GLYPH_NONE     , 0.654206f, 0.065421f, false, false,  -1, true  },
    { 1097, "\xd1" "\x89", GLYPH_NONE     , 0.747664f, 0.065421f, false, false,  -1, true  },
    { 1079, "\xd0" "\xb7", GLYPH_NONE     , 0.841121f, 0.065421f, false, false,  -1, true  },
    { 1093, "\xd1" "\x85", GLYPH_NONE     , 0.934579f, 0.065421f, false, true ,  -1, true  },
};
static const OskKey kXKeys_russian_r2[] = {
    { 1092, "\xd1" "\x84", GLYPH_NONE     , 0.000000f, 0.065421f, true , false,  -1, true  },
    { 1099, "\xd1" "\x8b", GLYPH_NONE     , 0.093458f, 0.065421f, false, false,  -1, true  },
    { 1074, "\xd0" "\xb2", GLYPH_NONE     , 0.186916f, 0.065421f, false, false,  -1, true  },
    { 1072, "\xd0" "\xb0", GLYPH_NONE     , 0.280374f, 0.065421f, false, false,  -1, true  },
    { 1087, "\xd0" "\xbf", GLYPH_NONE     , 0.373832f, 0.065421f, false, false,  -1, true  },
    { 1088, "\xd1" "\x80", GLYPH_NONE     , 0.467290f, 0.065421f, false, false,  -1, true  },
    { 1086, "\xd0" "\xbe", GLYPH_NONE     , 0.560748f, 0.065421f, false, false,  -1, true  },
    { 1083, "\xd0" "\xbb", GLYPH_NONE     , 0.654206f, 0.065421f, false, false,  -1, true  },
    { 1076, "\xd0" "\xb4", GLYPH_NONE     , 0.747664f, 0.065421f, false, false,  -1, true  },
    { 1078, "\xd0" "\xb6", GLYPH_NONE     , 0.841121f, 0.065421f, false, false,  -1, true  },
    { 1101, "\xd1" "\x8d", GLYPH_NONE     , 0.934579f, 0.065421f, false, true ,  -1, true  },
};
static const OskKey kXKeys_russian_r3[] = {
    { 1103, "\xd1" "\x8f", GLYPH_NONE     , 0.000000f, 0.065421f, true , false,  -1, true  },
    { 1095, "\xd1" "\x87", GLYPH_NONE     , 0.093458f, 0.065421f, false, false,  -1, true  },
    { 1089, "\xd1" "\x81", GLYPH_NONE     , 0.186916f, 0.065421f, false, false,  -1, true  },
    { 1084, "\xd0" "\xbc", GLYPH_NONE     , 0.280374f, 0.065421f, false, false,  -1, true  },
    { 1080, "\xd0" "\xb8", GLYPH_NONE     , 0.373832f, 0.065421f, false, false,  -1, true  },
    { 1090, "\xd1" "\x82", GLYPH_NONE     , 0.467290f, 0.065421f, false, false,  -1, true  },
    { 1100, "\xd1" "\x8c", GLYPH_NONE     , 0.560748f, 0.065421f, false, false,  -1, true  },
    { 1073, "\xd0" "\xb1", GLYPH_NONE     , 0.654206f, 0.065421f, false, false,  -1, true  },
    { 1102, "\xd1" "\x8e", GLYPH_NONE     , 0.747664f, 0.065421f, false, false,  -1, true  },
    { 1105, "\xd1" "\x91", GLYPH_NONE     , 0.841121f, 0.065421f, false, false,  -1, true  },
    { 1098, "\xd1" "\x8a", GLYPH_NONE     , 0.934579f, 0.065421f, false, true ,  -1, true  },
};
static const OskKey kXKeys_russian_r4[] = {
    {   -2, "?!#"       , GLYPH_SYMBOLS  , 0.000000f, 0.065421f, true , false,  -1, false },
    {   -1, "Shift"     , GLYPH_SHIFT_OFF, 0.093458f, 0.065421f, false, false,  -1, false },
    {   32, "Space"     , GLYPH_SPACE    , 0.186916f, 0.626168f, false, false,  -1, false },
    {   -3, "Left"      , GLYPH_LEFT     , 0.841121f, 0.065421f, false, false,  -1, false },
    {   -4, "Right"     , GLYPH_RIGHT    , 0.934579f, 0.065421f, false, true ,  -1, false },
};
static const OskRow kXRows_russian[] = {
    { 0.000000f, 0.162791f, true , false, kXKeys_russian_r0, 11 },
    { 0.209302f, 0.162791f, false, false, kXKeys_russian_r1, 11 },
    { 0.418605f, 0.162791f, false, false, kXKeys_russian_r2, 11 },
    { 0.627907f, 0.162791f, false, false, kXKeys_russian_r3, 11 },
    { 0.837209f, 0.162791f, false, true , kXKeys_russian_r4, 5 },
};
static const OskKeyboard kKb_russian = { kXRows_russian, 5 };

static const OskKey kXKeys_greek_r0[] = {
    {   49, "1"         , GLYPH_NONE     , 0.000000f, 0.065421f, true , false,  -1, false },
    {   50, "2"         , GLYPH_NONE     , 0.093458f, 0.065421f, false, false,  -1, false },
    {   51, "3"         , GLYPH_NONE     , 0.186916f, 0.065421f, false, false,  -1, false },
    {   52, "4"         , GLYPH_NONE     , 0.280374f, 0.065421f, false, false,  -1, false },
    {   53, "5"         , GLYPH_NONE     , 0.373832f, 0.065421f, false, false,  -1, false },
    {   54, "6"         , GLYPH_NONE     , 0.467290f, 0.065421f, false, false,  -1, false },
    {   55, "7"         , GLYPH_NONE     , 0.560748f, 0.065421f, false, false,  -1, false },
    {   56, "8"         , GLYPH_NONE     , 0.654206f, 0.065421f, false, false,  -1, false },
    {   57, "9"         , GLYPH_NONE     , 0.747664f, 0.065421f, false, false,  -1, false },
    {   48, "0"         , GLYPH_NONE     , 0.841121f, 0.065421f, false, false,  -1, false },
    {   -5, "Delete"    , GLYPH_DELETE   , 0.934579f, 0.065421f, false, true ,  -1, false },
};
static const OskKey kXKeys_greek_r1[] = {
    {  962, "\xcf" "\x82", GLYPH_NONE     , 0.093458f, 0.065421f, true , false,  -1, true  },
    {  949, "\xce" "\xb5", GLYPH_NONE     , 0.186916f, 0.065421f, false, false,  -1, true  },
    {  961, "\xcf" "\x81", GLYPH_NONE     , 0.280374f, 0.065421f, false, false,  -1, true  },
    {  964, "\xcf" "\x84", GLYPH_NONE     , 0.373832f, 0.065421f, false, false,  -1, true  },
    {  965, "\xcf" "\x85", GLYPH_NONE     , 0.467290f, 0.065421f, false, false,  -1, true  },
    {  952, "\xce" "\xb8", GLYPH_NONE     , 0.560748f, 0.065421f, false, false,  -1, true  },
    {  953, "\xce" "\xb9", GLYPH_NONE     , 0.654206f, 0.065421f, false, false,  -1, true  },
    {  959, "\xce" "\xbf", GLYPH_NONE     , 0.747664f, 0.065421f, false, false,  -1, true  },
    {  960, "\xcf" "\x80", GLYPH_NONE     , 0.841121f, 0.065421f, false, true ,  -1, true  },
};
static const OskKey kXKeys_greek_r2[] = {
    {  945, "\xce" "\xb1", GLYPH_NONE     , 0.093458f, 0.065421f, true , false,  -1, true  },
    {  963, "\xcf" "\x83", GLYPH_NONE     , 0.186916f, 0.065421f, false, false,  -1, true  },
    {  948, "\xce" "\xb4", GLYPH_NONE     , 0.280374f, 0.065421f, false, false,  -1, true  },
    {  966, "\xcf" "\x86", GLYPH_NONE     , 0.373832f, 0.065421f, false, false,  -1, true  },
    {  947, "\xce" "\xb3", GLYPH_NONE     , 0.467290f, 0.065421f, false, false,  -1, true  },
    {  951, "\xce" "\xb7", GLYPH_NONE     , 0.560748f, 0.065421f, false, false,  -1, true  },
    {  958, "\xce" "\xbe", GLYPH_NONE     , 0.654206f, 0.065421f, false, false,  -1, true  },
    {  954, "\xce" "\xba", GLYPH_NONE     , 0.747664f, 0.065421f, false, false,  -1, true  },
    {  955, "\xce" "\xbb", GLYPH_NONE     , 0.841121f, 0.065421f, false, true ,  -1, true  },
};
static const OskKey kXKeys_greek_r3[] = {
    {  950, "\xce" "\xb6", GLYPH_NONE     , 0.186916f, 0.065421f, true , false,  -1, true  },
    {  967, "\xcf" "\x87", GLYPH_NONE     , 0.280374f, 0.065421f, false, false,  -1, true  },
    {  968, "\xcf" "\x88", GLYPH_NONE     , 0.373832f, 0.065421f, false, false,  -1, true  },
    {  969, "\xcf" "\x89", GLYPH_NONE     , 0.467290f, 0.065421f, false, false,  -1, true  },
    {  946, "\xce" "\xb2", GLYPH_NONE     , 0.560748f, 0.065421f, false, false,  -1, true  },
    {  957, "\xce" "\xbd", GLYPH_NONE     , 0.654206f, 0.065421f, false, false,  -1, true  },
    {  956, "\xce" "\xbc", GLYPH_NONE     , 0.747664f, 0.065421f, false, true ,  -1, true  },
};
static const OskKey kXKeys_greek_r4[] = {
    {   -2, "?!#"       , GLYPH_SYMBOLS  , 0.000000f, 0.065421f, true , false,  -1, false },
    {   -1, "Shift"     , GLYPH_SHIFT_OFF, 0.093458f, 0.065421f, false, false,  -1, false },
    {   32, "Space"     , GLYPH_SPACE    , 0.186916f, 0.626168f, false, false,  -1, false },
    {   -3, "Left"      , GLYPH_LEFT     , 0.841121f, 0.065421f, false, false,  -1, false },
    {   -4, "Right"     , GLYPH_RIGHT    , 0.934579f, 0.065421f, false, true ,  -1, false },
};
static const OskRow kXRows_greek[] = {
    { 0.000000f, 0.162791f, true , false, kXKeys_greek_r0, 11 },
    { 0.209302f, 0.162791f, false, false, kXKeys_greek_r1, 9 },
    { 0.418605f, 0.162791f, false, false, kXKeys_greek_r2, 9 },
    { 0.627907f, 0.162791f, false, false, kXKeys_greek_r3, 7 },
    { 0.837209f, 0.162791f, false, true , kXKeys_greek_r4, 5 },
};
static const OskKeyboard kKb_greek = { kXRows_greek, 5 };

static const OskKey kXKeys_hebrew_r0[] = {
    {   49, "1"         , GLYPH_NONE     , 0.000000f, 0.065421f, true , false,  -1, false },
    {   50, "2"         , GLYPH_NONE     , 0.093458f, 0.065421f, false, false,  -1, false },
    {   51, "3"         , GLYPH_NONE     , 0.186916f, 0.065421f, false, false,  -1, false },
    {   52, "4"         , GLYPH_NONE     , 0.280374f, 0.065421f, false, false,  -1, false },
    {   53, "5"         , GLYPH_NONE     , 0.373832f, 0.065421f, false, false,  -1, false },
    {   54, "6"         , GLYPH_NONE     , 0.467290f, 0.065421f, false, false,  -1, false },
    {   55, "7"         , GLYPH_NONE     , 0.560748f, 0.065421f, false, false,  -1, false },
    {   56, "8"         , GLYPH_NONE     , 0.654206f, 0.065421f, false, false,  -1, false },
    {   57, "9"         , GLYPH_NONE     , 0.747664f, 0.065421f, false, false,  -1, false },
    {   48, "0"         , GLYPH_NONE     , 0.841121f, 0.065421f, false, false,  -1, false },
    {   -5, "Delete"    , GLYPH_DELETE   , 0.934579f, 0.065421f, false, true ,  -1, false },
};
static const OskKey kXKeys_hebrew_r1[] = {
    { 1511, "\xd7" "\xa7", GLYPH_NONE     , 0.093458f, 0.065421f, true , false,  -1, false },
    { 1512, "\xd7" "\xa8", GLYPH_NONE     , 0.186916f, 0.065421f, false, false,  -1, false },
    { 1488, "\xd7" "\x90", GLYPH_NONE     , 0.280374f, 0.065421f, false, false,  -1, false },
    { 1496, "\xd7" "\x98", GLYPH_NONE     , 0.373832f, 0.065421f, false, false,  -1, false },
    { 1493, "\xd7" "\x95", GLYPH_NONE     , 0.467290f, 0.065421f, false, false,  -1, false },
    { 1503, "\xd7" "\x9f", GLYPH_NONE     , 0.560748f, 0.065421f, false, false,  -1, false },
    { 1501, "\xd7" "\x9d", GLYPH_NONE     , 0.654206f, 0.065421f, false, false,  -1, false },
    { 1508, "\xd7" "\xa4", GLYPH_NONE     , 0.747664f, 0.065421f, false, false,  -1, false },
    { 1507, "\xd7" "\xa3", GLYPH_NONE     , 0.841121f, 0.065421f, false, true ,  -1, false },
};
static const OskKey kXKeys_hebrew_r2[] = {
    { 1513, "\xd7" "\xa9", GLYPH_NONE     , 0.093458f, 0.065421f, true , false,  -1, false },
    { 1491, "\xd7" "\x93", GLYPH_NONE     , 0.186916f, 0.065421f, false, false,  -1, false },
    { 1490, "\xd7" "\x92", GLYPH_NONE     , 0.280374f, 0.065421f, false, false,  -1, false },
    { 1499, "\xd7" "\x9b", GLYPH_NONE     , 0.373832f, 0.065421f, false, false,  -1, false },
    { 1506, "\xd7" "\xa2", GLYPH_NONE     , 0.467290f, 0.065421f, false, false,  -1, false },
    { 1497, "\xd7" "\x99", GLYPH_NONE     , 0.560748f, 0.065421f, false, false,  -1, false },
    { 1495, "\xd7" "\x97", GLYPH_NONE     , 0.654206f, 0.065421f, false, false,  -1, false },
    { 1500, "\xd7" "\x9c", GLYPH_NONE     , 0.747664f, 0.065421f, false, false,  -1, false },
    { 1498, "\xd7" "\x9a", GLYPH_NONE     , 0.841121f, 0.065421f, false, true ,  -1, false },
};
static const OskKey kXKeys_hebrew_r3[] = {
    { 1494, "\xd7" "\x96", GLYPH_NONE     , 0.093458f, 0.065421f, true , false,  -1, false },
    { 1505, "\xd7" "\xa1", GLYPH_NONE     , 0.186916f, 0.065421f, false, false,  -1, false },
    { 1489, "\xd7" "\x91", GLYPH_NONE     , 0.280374f, 0.065421f, false, false,  -1, false },
    { 1492, "\xd7" "\x94", GLYPH_NONE     , 0.373832f, 0.065421f, false, false,  -1, false },
    { 1504, "\xd7" "\xa0", GLYPH_NONE     , 0.467290f, 0.065421f, false, false,  -1, false },
    { 1502, "\xd7" "\x9e", GLYPH_NONE     , 0.560748f, 0.065421f, false, false,  -1, false },
    { 1510, "\xd7" "\xa6", GLYPH_NONE     , 0.654206f, 0.065421f, false, false,  -1, false },
    { 1514, "\xd7" "\xaa", GLYPH_NONE     , 0.747664f, 0.065421f, false, false,  -1, false },
    { 1509, "\xd7" "\xa5", GLYPH_NONE     , 0.841121f, 0.065421f, false, true ,  -1, false },
};
static const OskKey kXKeys_hebrew_r4[] = {
    {   -2, "?!#"       , GLYPH_SYMBOLS  , 0.000000f, 0.065421f, true , false,  -1, false },
    {   -1, "Shift"     , GLYPH_SHIFT_OFF, 0.093458f, 0.065421f, false, false,  -1, false },
    {   32, "Space"     , GLYPH_SPACE    , 0.186916f, 0.626168f, false, false,  -1, false },
    {   -3, "Left"      , GLYPH_LEFT     , 0.841121f, 0.065421f, false, false,  -1, false },
    {   -4, "Right"     , GLYPH_RIGHT    , 0.934579f, 0.065421f, false, true ,  -1, false },
};
static const OskRow kXRows_hebrew[] = {
    { 0.000000f, 0.162791f, true , false, kXKeys_hebrew_r0, 11 },
    { 0.209302f, 0.162791f, false, false, kXKeys_hebrew_r1, 9 },
    { 0.418605f, 0.162791f, false, false, kXKeys_hebrew_r2, 9 },
    { 0.627907f, 0.162791f, false, false, kXKeys_hebrew_r3, 9 },
    { 0.837209f, 0.162791f, false, true , kXKeys_hebrew_r4, 5 },
};
static const OskKeyboard kKb_hebrew = { kXRows_hebrew, 5 };

static const OskKey kXKeys_thai_r0[] = {
    {   49, "1"         , GLYPH_NONE     , 0.000000f, 0.065421f, true , false,  -1, false },
    {   50, "2"         , GLYPH_NONE     , 0.093458f, 0.065421f, false, false,  -1, false },
    {   51, "3"         , GLYPH_NONE     , 0.186916f, 0.065421f, false, false,  -1, false },
    {   52, "4"         , GLYPH_NONE     , 0.280374f, 0.065421f, false, false,  -1, false },
    {   53, "5"         , GLYPH_NONE     , 0.373832f, 0.065421f, false, false,  -1, false },
    {   54, "6"         , GLYPH_NONE     , 0.467290f, 0.065421f, false, false,  -1, false },
    {   55, "7"         , GLYPH_NONE     , 0.560748f, 0.065421f, false, false,  -1, false },
    {   56, "8"         , GLYPH_NONE     , 0.654206f, 0.065421f, false, false,  -1, false },
    {   57, "9"         , GLYPH_NONE     , 0.747664f, 0.065421f, false, false,  -1, false },
    {   48, "0"         , GLYPH_NONE     , 0.841121f, 0.065421f, false, false,  -1, false },
    {   -5, "Delete"    , GLYPH_DELETE   , 0.934579f, 0.065421f, false, true ,  -1, false },
};
static const OskKey kXKeys_thai_r1[] = {
    { 3654, "\xe0" "\xb9" "\x86", GLYPH_NONE     , -0.046729f, 0.065421f, true , false,  -1, false },
    { 3652, "\xe0" "\xb9" "\x84", GLYPH_NONE     , 0.046729f, 0.065421f, false, false,  -1, false },
    { 3635, "\xe0" "\xb8" "\xb3", GLYPH_NONE     , 0.140187f, 0.065421f, false, false,  -1, false },
    { 3614, "\xe0" "\xb8" "\x9e", GLYPH_NONE     , 0.233645f, 0.065421f, false, false,  -1, false },
    { 3632, "\xe0" "\xb8" "\xb0", GLYPH_NONE     , 0.327103f, 0.065421f, false, false,  -1, false },
    { 3633, "\xe0" "\xb8" "\xb1", GLYPH_NONE     , 0.420561f, 0.065421f, false, false,  -1, false },
    { 3637, "\xe0" "\xb8" "\xb5", GLYPH_NONE     , 0.514019f, 0.065421f, false, false,  -1, false },
    { 3619, "\xe0" "\xb8" "\xa3", GLYPH_NONE     , 0.607477f, 0.065421f, false, false,  -1, false },
    { 3609, "\xe0" "\xb8" "\x99", GLYPH_NONE     , 0.700935f, 0.065421f, false, false,  -1, false },
    { 3618, "\xe0" "\xb8" "\xa2", GLYPH_NONE     , 0.794393f, 0.065421f, false, false,  -1, false },
    { 3610, "\xe0" "\xb8" "\x9a", GLYPH_NONE     , 0.887850f, 0.065421f, false, false,  -1, false },
    { 3621, "\xe0" "\xb8" "\xa5", GLYPH_NONE     , 0.981308f, 0.065421f, false, true ,  -1, false },
};
static const OskKey kXKeys_thai_r2[] = {
    { 3615, "\xe0" "\xb8" "\x9f", GLYPH_NONE     , 0.000000f, 0.065421f, true , false,  -1, false },
    { 3627, "\xe0" "\xb8" "\xab", GLYPH_NONE     , 0.093458f, 0.065421f, false, false,  -1, false },
    { 3585, "\xe0" "\xb8" "\x81", GLYPH_NONE     , 0.186916f, 0.065421f, false, false,  -1, false },
    { 3604, "\xe0" "\xb8" "\x94", GLYPH_NONE     , 0.280374f, 0.065421f, false, false,  -1, false },
    { 3648, "\xe0" "\xb9" "\x80", GLYPH_NONE     , 0.373832f, 0.065421f, false, false,  -1, false },
    { 3657, "\xe0" "\xb9" "\x89", GLYPH_NONE     , 0.467290f, 0.065421f, false, false,  -1, false },
    { 3656, "\xe0" "\xb9" "\x88", GLYPH_NONE     , 0.560748f, 0.065421f, false, false,  -1, false },
    { 3634, "\xe0" "\xb8" "\xb2", GLYPH_NONE     , 0.654206f, 0.065421f, false, false,  -1, false },
    { 3626, "\xe0" "\xb8" "\xaa", GLYPH_NONE     , 0.747664f, 0.065421f, false, false,  -1, false },
    { 3623, "\xe0" "\xb8" "\xa7", GLYPH_NONE     , 0.841121f, 0.065421f, false, false,  -1, false },
    { 3591, "\xe0" "\xb8" "\x87", GLYPH_NONE     , 0.934579f, 0.065421f, false, true ,  -1, false },
};
static const OskKey kXKeys_thai_r3[] = {
    { 3612, "\xe0" "\xb8" "\x9c", GLYPH_NONE     , 0.046729f, 0.065421f, true , false,  -1, false },
    { 3611, "\xe0" "\xb8" "\x9b", GLYPH_NONE     , 0.140187f, 0.065421f, false, false,  -1, false },
    { 3649, "\xe0" "\xb9" "\x81", GLYPH_NONE     , 0.233645f, 0.065421f, false, false,  -1, false },
    { 3629, "\xe0" "\xb8" "\xad", GLYPH_NONE     , 0.327103f, 0.065421f, false, false,  -1, false },
    { 3636, "\xe0" "\xb8" "\xb4", GLYPH_NONE     , 0.420561f, 0.065421f, false, false,  -1, false },
    { 3639, "\xe0" "\xb8" "\xb7", GLYPH_NONE     , 0.514019f, 0.065421f, false, false,  -1, false },
    { 3607, "\xe0" "\xb8" "\x97", GLYPH_NONE     , 0.607477f, 0.065421f, false, false,  -1, false },
    { 3617, "\xe0" "\xb8" "\xa1", GLYPH_NONE     , 0.700935f, 0.065421f, false, false,  -1, false },
    { 3651, "\xe0" "\xb9" "\x83", GLYPH_NONE     , 0.794393f, 0.065421f, false, false,  -1, false },
    { 3613, "\xe0" "\xb8" "\x9d", GLYPH_NONE     , 0.887850f, 0.065421f, false, true ,  -1, false },
};
static const OskKey kXKeys_thai_r4[] = {
    {   -2, "?!#"       , GLYPH_SYMBOLS  , 0.000000f, 0.065421f, true , false,  -1, false },
    {   -1, "Shift"     , GLYPH_SHIFT_OFF, 0.093458f, 0.065421f, false, false,  -1, false },
    {   32, "Space"     , GLYPH_SPACE    , 0.186916f, 0.626168f, false, false,  -1, false },
    {   -3, "Left"      , GLYPH_LEFT     , 0.841121f, 0.065421f, false, false,  -1, false },
    {   -4, "Right"     , GLYPH_RIGHT    , 0.934579f, 0.065421f, false, true ,  -1, false },
};
static const OskRow kXRows_thai[] = {
    { 0.000000f, 0.162791f, true , false, kXKeys_thai_r0, 11 },
    { 0.209302f, 0.162791f, false, false, kXKeys_thai_r1, 12 },
    { 0.418605f, 0.162791f, false, false, kXKeys_thai_r2, 11 },
    { 0.627907f, 0.162791f, false, false, kXKeys_thai_r3, 10 },
    { 0.837209f, 0.162791f, false, true , kXKeys_thai_r4, 5 },
};
static const OskKeyboard kKb_thai = { kXRows_thai, 5 };

static const OskKey kXKeys_arabic_r0[] = {
    {   49, "1"         , GLYPH_NONE     , 0.000000f, 0.065421f, true , false,  -1, false },
    {   50, "2"         , GLYPH_NONE     , 0.093458f, 0.065421f, false, false,  -1, false },
    {   51, "3"         , GLYPH_NONE     , 0.186916f, 0.065421f, false, false,  -1, false },
    {   52, "4"         , GLYPH_NONE     , 0.280374f, 0.065421f, false, false,  -1, false },
    {   53, "5"         , GLYPH_NONE     , 0.373832f, 0.065421f, false, false,  -1, false },
    {   54, "6"         , GLYPH_NONE     , 0.467290f, 0.065421f, false, false,  -1, false },
    {   55, "7"         , GLYPH_NONE     , 0.560748f, 0.065421f, false, false,  -1, false },
    {   56, "8"         , GLYPH_NONE     , 0.654206f, 0.065421f, false, false,  -1, false },
    {   57, "9"         , GLYPH_NONE     , 0.747664f, 0.065421f, false, false,  -1, false },
    {   48, "0"         , GLYPH_NONE     , 0.841121f, 0.065421f, false, false,  -1, false },
    {   -5, "Delete"    , GLYPH_DELETE   , 0.934579f, 0.065421f, false, true ,  -1, false },
};
static const OskKey kXKeys_arabic_r1[] = {
    { 1590, "\xd8" "\xb6", GLYPH_NONE     , 0.000000f, 0.065421f, true , false,  -1, false },
    { 1589, "\xd8" "\xb5", GLYPH_NONE     , 0.093458f, 0.065421f, false, false,  -1, false },
    { 1579, "\xd8" "\xab", GLYPH_NONE     , 0.186916f, 0.065421f, false, false,  -1, false },
    { 1602, "\xd9" "\x82", GLYPH_NONE     , 0.280374f, 0.065421f, false, false,  -1, false },
    { 1601, "\xd9" "\x81", GLYPH_NONE     , 0.373832f, 0.065421f, false, false,  -1, false },
    { 1594, "\xd8" "\xba", GLYPH_NONE     , 0.467290f, 0.065421f, false, false,  -1, false },
    { 1593, "\xd8" "\xb9", GLYPH_NONE     , 0.560748f, 0.065421f, false, false,  -1, false },
    { 1607, "\xd9" "\x87", GLYPH_NONE     , 0.654206f, 0.065421f, false, false,  -1, false },
    { 1582, "\xd8" "\xae", GLYPH_NONE     , 0.747664f, 0.065421f, false, false,  -1, false },
    { 1581, "\xd8" "\xad", GLYPH_NONE     , 0.841121f, 0.065421f, false, false,  -1, false },
    { 1580, "\xd8" "\xac", GLYPH_NONE     , 0.934579f, 0.065421f, false, true ,  -1, false },
};
static const OskKey kXKeys_arabic_r2[] = {
    { 1588, "\xd8" "\xb4", GLYPH_NONE     , 0.000000f, 0.065421f, true , false,  -1, false },
    { 1587, "\xd8" "\xb3", GLYPH_NONE     , 0.093458f, 0.065421f, false, false,  -1, false },
    { 1610, "\xd9" "\x8a", GLYPH_NONE     , 0.186916f, 0.065421f, false, false,  -1, false },
    { 1576, "\xd8" "\xa8", GLYPH_NONE     , 0.280374f, 0.065421f, false, false,  -1, false },
    { 1604, "\xd9" "\x84", GLYPH_NONE     , 0.373832f, 0.065421f, false, false,  -1, false },
    { 1575, "\xd8" "\xa7", GLYPH_NONE     , 0.467290f, 0.065421f, false, false,  -1, false },
    { 1578, "\xd8" "\xaa", GLYPH_NONE     , 0.560748f, 0.065421f, false, false,  -1, false },
    { 1606, "\xd9" "\x86", GLYPH_NONE     , 0.654206f, 0.065421f, false, false,  -1, false },
    { 1605, "\xd9" "\x85", GLYPH_NONE     , 0.747664f, 0.065421f, false, false,  -1, false },
    { 1603, "\xd9" "\x83", GLYPH_NONE     , 0.841121f, 0.065421f, false, false,  -1, false },
    { 1591, "\xd8" "\xb7", GLYPH_NONE     , 0.934579f, 0.065421f, false, true ,  -1, false },
};
static const OskKey kXKeys_arabic_r3[] = {
    { 1584, "\xd8" "\xb0", GLYPH_NONE     , 0.046729f, 0.065421f, true , false,  -1, false },
    { 1569, "\xd8" "\xa1", GLYPH_NONE     , 0.140187f, 0.065421f, false, false,  -1, false },
    { 1572, "\xd8" "\xa4", GLYPH_NONE     , 0.233645f, 0.065421f, false, false,  -1, false },
    { 1585, "\xd8" "\xb1", GLYPH_NONE     , 0.327103f, 0.065421f, false, false,  -1, false },
    { 1609, "\xd9" "\x89", GLYPH_NONE     , 0.420561f, 0.065421f, false, false,  -1, false },
    { 1577, "\xd8" "\xa9", GLYPH_NONE     , 0.514019f, 0.065421f, false, false,  -1, false },
    { 1608, "\xd9" "\x88", GLYPH_NONE     , 0.607477f, 0.065421f, false, false,  -1, false },
    { 1586, "\xd8" "\xb2", GLYPH_NONE     , 0.700935f, 0.065421f, false, false,  -1, false },
    { 1592, "\xd8" "\xb8", GLYPH_NONE     , 0.794393f, 0.065421f, false, false,  -1, false },
    { 1583, "\xd8" "\xaf", GLYPH_NONE     , 0.887850f, 0.065421f, false, true ,  -1, false },
};
static const OskKey kXKeys_arabic_r4[] = {
    {   -2, "?!#"       , GLYPH_SYMBOLS  , 0.000000f, 0.065421f, true , false,  -1, false },
    {   -1, "Shift"     , GLYPH_SHIFT_OFF, 0.093458f, 0.065421f, false, false,  -1, false },
    {   32, "Space"     , GLYPH_SPACE    , 0.186916f, 0.626168f, false, false,  -1, false },
    {   -3, "Left"      , GLYPH_LEFT     , 0.841121f, 0.065421f, false, false,  -1, false },
    {   -4, "Right"     , GLYPH_RIGHT    , 0.934579f, 0.065421f, false, true ,  -1, false },
};
static const OskRow kXRows_arabic[] = {
    { 0.000000f, 0.162791f, true , false, kXKeys_arabic_r0, 11 },
    { 0.209302f, 0.162791f, false, false, kXKeys_arabic_r1, 11 },
    { 0.418605f, 0.162791f, false, false, kXKeys_arabic_r2, 11 },
    { 0.627907f, 0.162791f, false, false, kXKeys_arabic_r3, 10 },
    { 0.837209f, 0.162791f, false, true , kXKeys_arabic_r4, 5 },
};
static const OskKeyboard kKb_arabic = { kXRows_arabic, 5 };

} // namespace android

#endif // GAMMAOS_NANO_OSK_LAYOUTS_EXTRA_H
